[slurm]
username = "$(whoami)"
# squeue_cmd = ""

[job_list]
refresh_interval = 5 # -1 to disable auto-refresh

[job_details]
refresh_interval = 5 # -1 to disable auto-refresh

[job_output]
refresh_interval = 5 # -1 to disable auto-refresh
lines = 100 # -1 to show all lines
line_number = true
